# Generated by Django 5.1.5 on 2025-02-08 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_property_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photos',
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='booking.property'),
        ),
    ]
