# Generated by Django 5.1.5 on 2025-03-17 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_registereduser_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='userloginactivity',
            name='timestamp',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='userloginactivity',
            name='user',
            field=models.DateField(null=True, blank=True),
        ),
    ]
