# Generated by Django 5.1.5 on 2025-03-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_amenity_alter_property_baths_alter_property_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(to='booking.amenity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='baths',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
