# Generated by Django 5.1.5 on 2025-03-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_remove_property_description_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(related_name='properties', to='booking.amenity'),
        ),
    ]
