# Generated by Django 5.1.5 on 2025-03-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_property_description_alter_property_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='custom_amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='booking.amenity'),
        ),
    ]
