# Generated by Django 5.1.5 on 2025-03-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_property_custom_amenities_alter_amenity_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='custom_amenities',
        ),
        migrations.AddField(
            model_name='amenity',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(related_name='properties', to='booking.amenity'),
        ),
    ]
