# Generated by Django 5.1.5 on 2025-03-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_remove_property_amenities_property_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='emoji',
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated list of amenities'),
        ),
    ]
