# Generated by Django 5.1.5 on 2025-03-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_amenity_icon_alter_property_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(default='', help_text="FontAwesome icon class, e.g., 'fas fa-wifi'", max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='booking.amenity'),
        ),
    ]
