# Generated by Django 5.1.7 on 2025-03-31 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_alter_amenity_icon_alter_property_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='addexclusive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=12)),
                ('location', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=50)),
                ('rooms', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='exclusivebookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=12)),
                ('location', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=50)),
                ('rooms', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExclusiveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exclusive_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='booking.addexclusive')),
            ],
        ),
    ]
