# Generated by Django 5.1.7 on 2025-04-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_addexclusive_exclusivebookings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexclusive',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='booking.amenity'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_related', to='booking.amenity'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(help_text="FontAwesome icon class, e.g., 'fas fa-wifi'", max_length=100),
        ),
    ]
