# Generated by Django 5.1.7 on 2025-04-04 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_addexclusive_amenities_amenity_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusiveimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_images', to='booking.addexclusive'),
        ),
    ]
