# Generated by Django 5.1.7 on 2025-04-04 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_alter_exclusiveimage_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusiveimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='booking.addexclusive'),
        ),
    ]
